//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MyExcelTest
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.IO;
    using System.Data;
    using Excel;

	internal class ExcelSheet
	{
		private bool fileExist;
        private DataSet result;
        private string name;

        public ExcelSheet()
        {
            fileExist = false;
            result = new DataSet();
        }

		public virtual void open(string fileName)
		{
            fileExist = File.Exists(fileName);
            
            if (!fileExist) return;

            name = Path.GetFileNameWithoutExtension(fileName);
            FileStream stream = File.Open(fileName, FileMode.Open, FileAccess.Read);

            IExcelDataReader excelReader = ExcelReaderFactory.CreateBinaryReader(stream);
            excelReader.IsFirstRowAsColumnNames = true;
            result = excelReader.AsDataSet();
            excelReader.Close();

		}

		public virtual int getTabCount()
		{
            if (!isOpen()) return 0;
            return result.Tables.Count;
		}

		public virtual string getTabName(int tabIndex)
		{
            if (!isOpen()) return "";
            if (tabIndex >= result.Tables.Count) return "";
            return result.Tables[tabIndex].TableName;
		}

		public virtual bool isOpen()
		{
            return fileExist;
		}

		public virtual DataSet getDataSet()
		{
            if (!fileExist) return null;
            return result;
		}


        internal string getName()
        {
            return name;
        }
    }
}

