#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMBF.Report
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TMBF")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TelecomContext"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CustomerBill> CustomerBills
		{
			get
			{
				return this.GetTable<CustomerBill>();
			}
		}
		
		public System.Data.Linq.Table<SummarySalesRepCommision> SummarySalesRepCommisions
		{
			get
			{
				return this.GetTable<SummarySalesRepCommision>();
			}
		}
		
		public System.Data.Linq.Table<TrafficSummary> TrafficSummaries
		{
			get
			{
				return this.GetTable<TrafficSummary>();
			}
		}
		
		public System.Data.Linq.Table<Rate> Rates
		{
			get
			{
				return this.GetTable<Rate>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerBill")]
	public partial class CustomerBill
	{
		
		private string _PhoneNo;
		
		private int _Length;
		
		private System.Nullable<System.DateTime> _CallDate;
		
		private string _CallTime;
		
		private System.Nullable<double> _Cost;
		
		public CustomerBill()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string PhoneNo
		{
			get
			{
				return this._PhoneNo;
			}
			set
			{
				if ((this._PhoneNo != value))
				{
					this._PhoneNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="Int NOT NULL")]
		public int Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				if ((this._Length != value))
				{
					this._Length = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CallDate
		{
			get
			{
				return this._CallDate;
			}
			set
			{
				if ((this._CallDate != value))
				{
					this._CallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallTime", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string CallTime
		{
			get
			{
				return this._CallTime;
			}
			set
			{
				if ((this._CallTime != value))
				{
					this._CallTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Float")]
		public System.Nullable<double> Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this._Cost = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SummarySalesRepCommision")]
	public partial class SummarySalesRepCommision
	{
		
		private string _SalesRepName;
		
		private System.Nullable<double> _Commission;
		
		public SummarySalesRepCommision()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesRepName", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SalesRepName
		{
			get
			{
				return this._SalesRepName;
			}
			set
			{
				if ((this._SalesRepName != value))
				{
					this._SalesRepName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Commission", DbType="Float")]
		public System.Nullable<double> Commission
		{
			get
			{
				return this._Commission;
			}
			set
			{
				if ((this._Commission != value))
				{
					this._Commission = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrafficSummary")]
	public partial class TrafficSummary
	{
		
		private string _ServiceName;
		
		private string _FromCountryName;
		
		private string _ToCountryName;
		
		private int _Duration;
		
		public TrafficSummary()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceName", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string ServiceName
		{
			get
			{
				return this._ServiceName;
			}
			set
			{
				if ((this._ServiceName != value))
				{
					this._ServiceName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromCountryName", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string FromCountryName
		{
			get
			{
				return this._FromCountryName;
			}
			set
			{
				if ((this._FromCountryName != value))
				{
					this._FromCountryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToCountryName", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ToCountryName
		{
			get
			{
				return this._ToCountryName;
			}
			set
			{
				if ((this._ToCountryName != value))
				{
					this._ToCountryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="Int NOT NULL")]
		public int Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this._Duration = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rate")]
	public partial class Rate
	{
		
		private string _DestinationCountryName;
		
		private System.Nullable<double> _PeekRate;
		
		private System.Nullable<double> _OffPeekRate;
		
		public Rate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationCountryName", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DestinationCountryName
		{
			get
			{
				return this._DestinationCountryName;
			}
			set
			{
				if ((this._DestinationCountryName != value))
				{
					this._DestinationCountryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeekRate", DbType="Float")]
		public System.Nullable<double> PeekRate
		{
			get
			{
				return this._PeekRate;
			}
			set
			{
				if ((this._PeekRate != value))
				{
					this._PeekRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OffPeekRate", DbType="Float")]
		public System.Nullable<double> OffPeekRate
		{
			get
			{
				return this._OffPeekRate;
			}
			set
			{
				if ((this._OffPeekRate != value))
				{
					this._OffPeekRate = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
