<?xml version="1.0" encoding="utf-8"?><Database Name="TMBF" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\v11.0;Initial Catalog=TMBF;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TelecomContext" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CustomerBill" Member="CustomerBills">
    <Type Name="CustomerBill">
      <Column Name="PhoneNo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CallDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CallTime" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SummarySalesRepCommision" Member="SummarySalesRepCommisions">
    <Type Name="SummarySalesRepCommision">
      <Column Name="SalesRepName" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Commission" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrafficSummary" Member="TrafficSummaries">
    <Type Name="TrafficSummary">
      <Column Name="ServiceName" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="FromCountryName" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="ToCountryName" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Rate" Member="Rates">
    <Type Name="Rate">
      <Column Name="CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DestinationCountryName" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="PeekRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OffPeekRate" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>