
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (1, N'USA')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (7, N'Russia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (20, N'Egypt')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (27, N'South Africa')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (30, N'Greece ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (31, N'Netherlands')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (32, N'Belgium')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (33, N'France')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (34, N'Spain')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (36, N'Hungary ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (39, N'Italy ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (40, N'Romania')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (41, N'Switzerland')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (43, N'Austria')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (44, N'United Kingdom')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (45, N'Denmark')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (46, N'Sweden')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (47, N'Norway ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (48, N'Poland')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (49, N'Germany')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (51, N'Peru')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (52, N'Mexico')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (53, N'Cuba')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (54, N'Argentina')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (55, N'Brazil ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (56, N'Chile ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (57, N'Colombia ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (58, N'Venezuela')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (60, N'Malaysia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (61, N'Australia ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (62, N'Indonesia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (63, N'Philippines')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (64, N'New Zealand')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (65, N'Singapore')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (66, N'Thailand')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (81, N'Japan ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (82, N'Korea (South)')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (84, N'Vietnam')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (86, N'China (PRC)')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (90, N'Turkey')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (91, N'India')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (92, N'Pakistan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (93, N'Afghanistan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (94, N'Sri Lanka')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (95, N'Myanmar')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (98, N'Iran')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (212, N'Morocco')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (213, N'Algeria')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (216, N'Tunisia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (218, N'Libya')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (220, N'Gambia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (221, N'Senegal ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (222, N'Mauritania')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (223, N'Mali Republic')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (224, N'Guinea')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (225, N'Côte d''Ivoire (Ivory Coast)')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (226, N'Burkina Faso ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (227, N'Niger')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (228, N'Togolese Republic')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (229, N'Benin')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (230, N'Mauritius')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (231, N'Liberia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (232, N'Sierra Leone')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (233, N'Ghana ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (234, N'Nigeria')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (235, N'Chad ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (236, N'Central African Republic')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (237, N'Cameroon')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (238, N'Cape Verde Islands')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (239, N'São Tomé and Principe')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (240, N'Equatorial Guinea')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (241, N'Gabonese Republic')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (242, N'Congo')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (243, N'"Congo, Dem. Rep. of "')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (244, N'Angola ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (245, N'Guinea-Bissau ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (246, N'Diego Garcia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (247, N'Ascension')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (248, N'Seychelles Republic')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (249, N'Sudan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (250, N'Rwandese Republic')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (251, N'Ethiopia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (252, N'Somali Democratic Republic')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (253, N'Djibouti')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (254, N'Kenya')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (255, N'Tanzania')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (256, N'Uganda')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (257, N'Burundi')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (258, N'Mozambique')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (260, N'Zambia ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (261, N'Madagascar')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (262, N'Réunion Island')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (263, N'Zimbabwe ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (264, N'Namibia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (265, N'Malawi ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (266, N'Lesotho')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (267, N'Botswana ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (268, N'Swaziland')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (269, N'Comoros')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (290, N'St. Helena')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (291, N'Eritrea')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (297, N'Aruba')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (298, N'Faroe Islands')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (299, N'Greenland ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (350, N'Gibraltar ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (351, N'Portugal')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (352, N'Luxembourg')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (353, N'Ireland')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (354, N'Iceland')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (355, N'Albania')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (356, N'Malta')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (357, N'Cyprus')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (358, N'Finland')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (359, N'Bulgaria')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (370, N'Lithuania ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (371, N'Latvia ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (372, N'Estonia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (373, N'Moldova ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (374, N'Armenia ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (375, N'Belarus')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (376, N'Andorra ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (377, N'Monaco')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (378, N'San Marino')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (379, N'Vatican City')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (380, N'Ukraine')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (381, N'Serbia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (382, N'Montenegro')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (385, N'Croatia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (386, N'Slovenia ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (387, N'Bosnia & Herzegovina ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (389, N'Macedonia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (420, N'Czech Republic')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (421, N'Slovak Republic')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (423, N'Liechtenstein')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (500, N'Falkland Islands')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (501, N'Belize')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (502, N'Guatemala ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (503, N'El Salvador')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (504, N'Honduras')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (505, N'Nicaragua')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (506, N'Costa Rica')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (507, N'Panama')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (508, N'St. Pierre & Miquelon')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (509, N'Haiti ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (590, N'Guadeloupe')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (591, N'Bolivia ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (592, N'Guyana')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (593, N'Ecuador ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (594, N'French Guiana')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (595, N'Paraguay')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (596, N'Martinique')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (597, N'Suriname ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (598, N'Uruguay')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (599, N'Curaçao')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (670, N'East Timor')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (672, N'Antarctica')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (673, N'Brunei Darussalam')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (674, N'Nauru')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (675, N'Papua New Guinea')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (676, N'Tonga Islands')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (677, N'Solomon Islands')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (678, N'Vanuatu')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (679, N'Fiji Islands')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (680, N'Palau')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (681, N'Wallis and Futuna Islands')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (682, N'Cook Islands')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (683, N'Niue')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (685, N'Samoa')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (686, N'Kiribati ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (687, N'New Caledonia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (688, N'Tuvalu')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (689, N'French Polynesia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (690, N'Tokelau')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (691, N'Micronesia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (692, N'Marshall Islands')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (808, N'Wake Island')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (850, N'Korea (North)')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (852, N'Hong Kong')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (853, N'Macao')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (855, N'Cambodia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (856, N'Laos')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (880, N'Bangladesh')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (886, N'Taiwan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (960, N'Maldives')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (961, N'Lebanon')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (962, N'Jordan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (963, N'Syria')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (964, N'Iraq')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (965, N'Kuwait ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (966, N'Saudi Arabia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (967, N'Yemen')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (968, N'Oman')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (971, N'United Arab Emirates')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (972, N'Israel ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (973, N'Bahrain')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (974, N'Qatar')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (975, N'Bhutan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (976, N'Mongolia ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (977, N'Nepal ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (992, N'Tajikistan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (993, N'Turkmenistan ')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (994, N'Azerbaijan')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (995, N'Georgia')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (996, N'Kyrgyz Republic')
INSERT INTO [dbo].[Country] ([ID], [Name]) VALUES (998, N'Uzbekistan')
